#!name=财新周刊会员
#!desc=财新周刊会员,登陆账号体验更加(2022.07.12)
#!openUrl=https://github.com/I-am-R-E/Functional-Store-Hub/tree/Master/CaiXinWeekly
#!author=@R·E https://t.me/Functional_Store_Hub

[Script]
财新周刊 = type=http-response,pattern=^https?:\/\/ipadcms\.caixin\.com\/(api|tmp|power)\/(articles?|myfree(v\d+)?),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/CaiXinWeekly/Script/CaiXinWeekly.js,script-update-interval=0

[MITM]
hostname = %APPEND% ipadcms.caixin.com
